// interface ActionTypeProps {
//     SET_PRODCUTS : string
//     SELECTED_PRODUCT: string
//     REMOVE_SELECTED_PRODUCT: string
// }
export const ActionTypes  = {
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
}